services:
  - name: cromi-nfc-backend
    type: web
    envs:
      - key: DJANGO_SECRET_KEY
        value: "cambia-esto-en-produccion"
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: ".koyeb.app,localhost,127.0.0.1"
      - key: SUPABASE_DB_NAME
        value: "PagoCruz"
      - key: SUPABASE_DB_USER
        value: "postgres"
      - key: SUPABASE_DB_PASSWORD
        value: "pagocruz"
      - key: SUPABASE_DB_HOST
        value: "oyfdbrufeqqofeixkzhj.supabase.co"
      - key: SUPABASE_DB_PORT
        value: "5432"
    build:
      type: buildpack
      buildpack_name: heroku/python
      install:
        - "pip install -r requirements.txt"
      build:
        - "python manage.py collectstatic --noinput"
        - "python manage.py migrate --noinput"
    run:
      cmd: "gunicorn nfc.wsgi --bind 0.0.0.0:$PORT"
