# Generated by Django 5.2.5 on 2025-08-30 07:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gremialista',
            fields=[
                ('id_gremialista', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Micro',
            fields=[
                ('id_micro', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linea', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MicroGremialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gremialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micros.gremialista')),
                ('id_micro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micros.micro')),
            ],
            options={
                'unique_together': {('id_micro', 'id_gremialista')},
            },
        ),
        migrations.AddField(
            model_name='micro',
            name='gremialistas',
            field=models.ManyToManyField(through='micros.MicroGremialista', to='micros.gremialista'),
        ),
    ]
